### ISSUE TITLE
Deriveの翻訳がThe Rust Programming Languageとずれている（導出と継承）

### ISSUE THREAD

**Issue by Hiroshiba** [rust-lang-ja/rust-by-example-ja#126]
`The Rust Programming Language`側ではDeriveの翻訳が「導出」となっていました。

- https://github.com/rust-lang-ja/book-ja/pull/40

google検索で先にヒットするこちらは「継承」なので、ちょっと混乱があるかもと思ってissueを作ってみました。

**Comment by dalance** [comment]
ありがとうございます。
変更しました。
