### ISSUE TITLE
続：シンタックスハイライトの復活

### ISSUE THREAD

**Issue by tatsuya6502** [rust-lang-ja/rust-by-example-ja#23]
[シンタックスハイライトが動作しない問題 #7](https://github.com/rust-lang-ja/rust-by-example-ja/issues/7) について、調べてみました。

https://github.com/rust-lang-ja/rust-by-example-ja/issues/7#issuecomment-222548351

> ロードの際のエラーをよくみると、失敗している原因は、
> http://rust-lang-ja.github.io/gitbook/plugins/gitbook-plugin-rust-playpen/mode-rust.js
> という誤ったURLからロードしようとしているからのようです。(`rust-by-example-ja` が抜けている)

中国語版サイトと比較してわかったのですが、以下を修正すれば、https://rust-lang-ja.org/rust-by-example/ で文書を表示できそうです。

ファイル：[rust-by-example-ja/node_modules/gitbook-plugin-rust-playpen/book/editor.js](https://github.com/rust-lang-ja/rust-by-example-ja/blob/4a876fd6e4572b8c06a27ea3b22d0f814cc0d0e1/node_modules/gitbook-plugin-rust-playpen/book/editor.js#L72)

**変更前：**

``` javascript
ace.config.setModuleUrl('ace/mode/rust', '/gitbook/plugins/gitbook-plugin-rust-playpen/mode-rust.js');
```

**変更後：**

``` javascript
ace.config.setModuleUrl('ace/mode/rust', '/rust-by-example/gitbook/plugins/gitbook-plugin-rust-playpen/mode-rust.js');
```

中国語版サイトでは、変更後と同じ設定を使っています。https://rustwiki.org/rust-by-example/gitbook/plugins/gitbook-plugin-rust-playpen/editor.js 

お時間のある時に、試してもらえないでしょうか？
よろしくお願いします。

**追記**：master ブランチ上の editor.js を変更すると、今度は、`make serve` が動かなくなってしまうので、`deploy.sh` で gh-pages にデプロイする時に、`sed` かなにかを使って書き換えるのがいいかもしれません。

**Comment by joemphilips** [comment]
ありがとうございます！大変助かります。

> 追記：master ブランチ上の editor.js を変更すると、今度は、make serve が動かなくなってしまう

これは、文書中のリンクを動作させるためにmarkdown中のリンクを絶対パスから相対パスに書き換えたことが原因のような気がします。

合わせて今週末までに直してみます。

**Comment by joemphilips** [comment]
以下のように修正しました。

urlを`rust-lang-ja.org/rust-by-example`に修正。
デプロイ時に`sed`で`gitbook-plugin-rust-playpen/book/editor.js`を修正

**Comment by tatsuya6502** [comment]
ありがとうございます！
