### ISSUE TITLE
rust-learning サイトへのリンク登録

### ISSUE THREAD

**Issue by tatsuya6502** [rust-lang-ja/rust-by-example-ja#24]
Rust by Example の和訳サイトを、公式サイトの Rust Documentation ページから辿れるように、[rust-learning](https://github.com/ctjhoa/rust-learning) に登録しようと思います。

以下の URL で、私から PR を上げようを思いますが、いいでしょうか？ > @joemphilips さん
- http://rust-lang-ja.org/rust-by-example/

---

ちなみに、公式サイトからは、以下の経路で辿ることになります。
1. 公式サイト Rust Documentation ページの [Non-english resources](https://www.rust-lang.org/documentation.html#non-english-resources) で、rust-learning へのリンクが紹介されている。
   
   > For resources in languages other than English, see the [locale-specific links in rust-learning](https://github.com/ctjhoa/rust-learning#locale-links).
2. [該当ページ](https://github.com/ctjhoa/rust-learning#locale-links) にアクセスして、[Japanese](https://github.com/ctjhoa/rust-learning/blob/master/ja_JP.md) のリンクをクリックする。
3. すると、以下のページが開く。現状は TRPL だけが載っている。
   https://github.com/ctjhoa/rust-learning/blob/master/ja_JP.md

**Comment by joemphilips** [comment]
ありがとうございます！ぜひお願い致します！

**Comment by tatsuya6502** [comment]
PR 上げましたー：https://github.com/ctjhoa/rust-learning/pull/52

**Comment by tatsuya6502** [comment]
PR がマージされたので、本件、クローズします。
