### ISSUE TITLE
誤訳を発見しました

### ISSUE THREAD

**Issue by snbn** [rust-lang-ja/rust-by-example-ja#46]
[ライフタイムの明示的アノーテーション](http://rust-lang-ja.org/rust-by-example/scope/lifetime/explicit.html)での記述で、原文では
> In this case, the lifetime of `foo` cannot exceed that of either `'a` *or* `'b`.

と書かれているのを、
> この場合は、`foo`のライフタイムは`'a`、`'b`の*どちらよりも*長くなければなりません。

と訳していますが、正しくは以下のようにするべきではないでしょうか。

> この場合は、`foo`のライフタイムは`'a`、`'b`の*どちらよりも*長くなってはなりません。

**Comment by joemphilips** [comment]
ありがとうございます。修正しました。
