### ISSUE TITLE
運用準備が整いました

### ISSUE THREAD

**Issue by joemphilips** [rust-lang-ja/rust-by-example-ja#5]
@KeenS @tatsuya6502 

一人で翻訳を進めていくつもりではありますが、だいぶ時間がかかりそうなので手伝っていただけたら
大変ありがたく思います。
アドバイスなどいただければ泣いて喜びます。

**Comment by KeenS** [comment]
お疲れ様です。微力ながら私もお手伝いさせて頂きます。

**Comment by tatsuya6502** [comment]
おつかれさまです。私もぜひお手伝いさせていただきます。来週くらいから、少し時間ができそうかな。

**Comment by joemphilips** [comment]
ありがとうございます。ダメ出しでもなんでも大歓迎です。
