### ISSUE TITLE
ソースコードの表示欄の縦幅が小さいです

### ISSUE THREAD

**Issue by TonalidadeHidrica** [rust-lang-ja/rust-by-example-ja#59]
日本語版ドキュメントのウェブサイトでは、サンプルコードが4行程度しか表示されません：

![image](https://user-images.githubusercontent.com/47710717/74402017-6668db00-4e66-11ea-9a7c-dde56452762b.png)

それに対して、本家英語版ウェブサイトではすべてのソースコードが表示されます：

![image](https://user-images.githubusercontent.com/47710717/74402054-7bde0500-4e66-11ea-83aa-2b9c375de126.png)

英語版サイトでも日本語版サイトと同じように、ソースコードをすべて表示されるようにすることは可能でしょうか？　現在の状態ですととても見にくいです。

**Comment by tatsuya6502** [comment]
ご報告ありがとうございます。日本語版サイトを公開したときは、ソースコードの全体が表示されていたのですが、いつの間にか壊れてしまったようです。サードパーティのJavaScriptなどを使用しているので、そちらで何かが変わったのかもしれません。

現在の日本語版サイトは、2016年ごろの英語版サイトの内容をベースにしていて、当時はgitbookというツールが使われていました。現在の英語版サイトはmdbookというツールに切り替わっています。日本語版サイトでもそちらに追従することでサンプルコードの表示の問題を解決できるかもしれません。

少し時間がかかりそうですが対応しようと思います。

**Comment by tatsuya6502** [comment]
> 現在の英語版サイトはmdbookというツールに切り替わっています。日本語版サイトでもそちらに追従することでサンプルコードの表示の問題を解決できるかもしれません。

先ほどプルリクエスト #66 をマージしました。ビルドツールがmdbookに切り替わり、内容も英語版の最新ものに追従しています。現状は一部が未翻訳ですが、少しずつ翻訳していく予定です。

ソースコードの表示欄の縦幅も直ったようですので、ご確認ください。
https://doc.rust-jp.rs/rust-by-example-ja/hello.html

**Comment by TonalidadeHidrica** [comment]
ご対応ありがとうございます。修正されたのを確認いたしました。
