### ISSUE TITLE
シンタックスハイライトを復活させる。

### ISSUE THREAD

**Issue by joemphilips** [rust-lang-ja/rust-by-example-ja#7]
TODO:
    日本語がrsファイルにまじるとシンタックスハイライトが機能しなくなっている。
    `src/`を見て原因を探る

**Comment by joemphilips** [comment]
`make serve`時にはハイライトされているので、`src/`以下ではなく`deploy.sh`に問題がある。

**Comment by joemphilips** [comment]
devlopers tool で確認したところlocalhost上の`source`には`ace/theme-tomorrow.js`が存在するのに対し、gh-pages上には存在しないので、これが原因と思われる。引き続き、その理由および本家のgh-pagesの状態を見ていく

**Comment by joemphilips** [comment]
全然わからないので、自分のデバッグスキルのなさを嘆きつつ
いったん断念

**Comment by joemphilips** [comment]
aceがmode-rust.jsをロードする際に

```
Failed to load resource: the server responded with a status of 404 (Not Found)
```

と出ている。しかし[github上には存在する](https://github.com/rust-lang-ja/rust-by-example-ja/blob/gh-pages/gitbook/plugins/gitbook-plugin-rust-playpen/mode-rust.js)ことから、github pagesがデプロイする際に問題が起きている可能性が高い。ローカルとの違いを考えると、ドメイン名のパスの長さが怪しいので、独自DNSの取得を試みる。

**Comment by keiichiw** [comment]
ロードの際のエラーをよくみると、失敗している原因は、
http://rust-lang-ja.github.io/gitbook/plugins/gitbook-plugin-rust-playpen/mode-rust.js
という誤ったURLからロードしようとしているからのようです。(`rust-by-example-ja` が抜けている)

正しいURLは http://rust-lang-ja.github.io/rust-by-example-ja/gitbook/plugins/gitbook-plugin-rust-playpen/mode-rust.js でこちらはちゃんとアクセスできるので、github pagesのデプロイの際に問題が起きているのではなく、JS側の問題だと思われます。

そのため、JSを書き換えるか、HTML内でのスクリプトのパスの書き方を修正するかで対応することも可能なのではないかと思います。
aceでは、スクリプトへのパスに関する設定は[この関数](https://github.com/ajaxorg/ace/blob/master/lib/ace/config.js#L146)でやっているようです（が解決策の調査はできていません）。

ただ、ドメイン取得をすれば、URL内の `/rust-by-example-ja/` の部分がいらなくなるので、確かに特に変更をせずに解決しそうですね。

**Comment by joemphilips** [comment]
ありがとうございます。

オリジナルのリポジトリでだいぶhackyなやり方をしていたのを、そのまま持ってきたのが原因ですね。
変に理解しようとこだわるよりもドメインをとってしまおうと思います。

そのうち本家がアップデートしたらまた考えます。

**Comment by joemphilips** [comment]
解決しました。
