### ISSUE TITLE
3.1 構造体のtypo?

### ISSUE THREAD

**Issue by hnakai0909** [rust-lang-ja/rust-by-example-ja#86]
[3.1章 構造体](https://doc.rust-jp.rs/rust-by-example-ja/custom_types/structs.html)
の冒頭にて、

> structというキーワードを用いて作成できる構造体（「structre」）には3種類あります。

とありますが，この**structre**はtypoではないでしょうか。

ただし、[struct.md](https://github.com/rust-lang-ja/rust-by-example-ja/blob/master/src/custom_types/structs.md) 7行目付近でコメントアウトされている原文をみると、

> There are three types of structures ("structs") that can be created using the
`struct` keyword:

とあり、「structures、あるいは略してstructs」という表現であると思われ、
日本語ではどちらも構造体と訳されると思われるため、このかっこ書きごと不要であるとも考えられます。

また、[TranslationTable.md](https://github.com/rust-lang-ja/rust-by-example-ja/blob/master/TranslationTable.md) では、structとstructureが構造体とストラクチャとして区別されていますが、実際の翻訳では今のところ「ストラクチャ」のほうは登場していないようです。

このように迷うところがあったので、PullRequestとはせずにIssueとさせていただきましたが、いかがでしょうか。

**Comment by dalance** [comment]
ご提案ありがとうございます。
ストラクチャについて調べてみたところ、TRPLの1.6の頃に「`enum`なども含めたデータ構造」という意味合いで登場したことがあるようです。

https://github.com/rust-lang-ja/the-rust-programming-language-ja/pull/3

その後1.9の翻訳では構造体に修正されたため現在は和訳ドキュメント全体から存在しなくなったようです。

https://github.com/rust-lang-ja/the-rust-programming-language-ja/pull/267

いずれにしても今回の文脈ではどちらも間違いなく構造体を指していると思いますので、
かっこ書きごと不要ということでいいのではないかと思います。

プルリクエスト出していただければマージします。

**Comment by hnakai0909** [comment]
レビューありがとうございます。
[PR #87 ](https://github.com/rust-lang-ja/rust-by-example-ja/pull/87)を作成しました。
よろしくお願いします。

**Comment by hnakai0909** [comment]
TranslationTable.md のほうも、変更したほうがよいでしょうか
(struct：構造体、structure：ストラクチャ　を両方とも　struct：構造体、structure：構造体　とする？)

**Comment by dalance** [comment]
そうですね。すでにその訳語を使っている箇所がないですし
ストラクチャという言葉も一般的ではないと思うので
変更でいいと思います。

**Comment by hnakai0909** [comment]
PR #88 を作成しました、よろしくお願いします。

**Comment by hnakai0909** [comment]
Mergeありがとうございました、本IssueはこれでCloseしようと思います。
